/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hard.rh.view;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Suporte-01
 */
public class ProgressBar extends java.awt.Frame {

    /**
     * Creates new form ProgressBar
     */
    public ProgressBar() {
        initComponents();
        configJanela();
        barra.setBounds(0, 20, 500, 50);
        barra.setStringPainted(true);
        barra.setValue(10);
        barra.setForeground(new Color(50, 200, 50));
        add(barra);
        new temp().start();
    }

    public void configJanela() {
        setTitle("Importando aguarde...");
        setLayout(null);
        setSize(500, 70);
        setLocationRelativeTo(null);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barra = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(500, 20));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        barra.setBorderPainted(false);
        barra.setEnabled(false);
        barra.setMaximumSize(new java.awt.Dimension(500, 20));
        barra.setMinimumSize(new java.awt.Dimension(500, 20));
        barra.setPreferredSize(new java.awt.Dimension(10, 20));
        add(barra, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    // End of variables declaration//GEN-END:variables

    public class temp extends Thread {

        public void run() {
            while (barra.getValue() < 100) {
                try {
                    sleep(10);
                    barra.setValue(barra.getValue() + 1);
                    if (Thread.interrupted()) {
                        throw new InterruptedException();
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(ProgressBar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            dispose();

        }

    }

}
